# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-04-17 16:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='locality',
            field=models.CharField(default='e.g Kigali, Nyagatare, Rusizi', max_length=30),
        ),
    ]
